/* COPYRIGHT (C) HARRY CLARK 2025 */

/* SEGA MEGA DRIVE EMULATOR */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY ENCOMPASSING */
/* THE MEMORY UTILITIES BETWEEN COMPONENTS AND THE CONNECTIONS BETWEEN THEM */

/* THIS FILE PROVIDES THE BASIC DEFINITIONS FOR M68K AND Z80 BUS COMMUNICATIONS */
/* AND RELEVANT PARSING AND WHATEVER THE CASE MAY BE AS PER DOCUMENTATION */

/* NESTED INCLUDES */

#include "mem.h"